### ISSUE TITLE
EPIC: Migration to GitLab for UDS Development

### ISSUE THREAD

**Issue by oates** [defenseunicorns/uds-software-factory#104]
This EPIC is to track the work left to migrate from Github to Gitlab for all things UDS Development. 
```[tasklist]
### SWF Tasks
- [ ] https://github.com/defenseunicorns/uds-infrastructure/issues/527
- [x] Setup connection/tokens needed to read/write to GHCR
- [x] UDS Releaser
- [x] Update <env> with uds-common, secrets and registry in preparation for active development use
- [ ] https://github.com/defenseunicorns/uds-software-factory/issues/92
- [ ] https://github.com/defenseunicorns/uds-software-factory/issues/106
- [ ] https://github.com/defenseunicorns/uds-software-factory/issues/108
- [ ] https://github.com/defenseunicorns/uds-software-factory/issues/107
- [ ] https://github.com/defenseunicorns/uds-image-builder/issues/18
- [ ] https://github.com/defenseunicorns/uds-infrastructure/issues/590
```

```[tasklist]
### Infra Tasks
- [ ] Backup Plan
- [ ] https://github.com/defenseunicorns/uds-infrastructure/issues/600
```

**Comment by joelmccoy** [comment]
Closing this to clean up our board a bit.  Don't think any further action is needed on this.
