### ISSUE TITLE
Features needed in support of SWF in shared UDS repositories

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-software-factory#11]
There are some issue we need to potentially pick up in support of SWF work in common repos. Currently identified are enhancements to the common tasks. 
```[tasklist]
### Tasks
- [ ] https://github.com/defenseunicorns/uds-common/issues/55
- [ ] https://github.com/defenseunicorns/uds-common/issues/54
- [ ] https://github.com/defenseunicorns/uds-common/issues/53
```
