### ISSUE TITLE
Publish a Unicorn Flavor for all SWF supported packages

### ISSUE THREAD

**Issue by oates** [defenseunicorns/uds-software-factory#112]
The App Store team requested we publish a Unicorn Flavor even for the packages we do not have hardened images for yet, as we plan to show the progress of our flavors vs upstream even if they are the same for now until we get to them. 
```[tasklist]
### Tasks
- [x] Publish unicorn flavor for GitLab
- [x] Publish unicorn flavor for Postgres
- [ ] https://github.com/defenseunicorns/uds-package-valkey/issues/45
- [ ] https://github.com/defenseunicorns/uds-package-minio-operator/issues/25
- [x] Publish unicorn flavor of Sigstore
- [ ] https://github.com/defenseunicorns/uds-package-archivista/issues/37
- [x] Publish unicorn flavor of Renovate
```
