### ISSUE TITLE
Update All Software Factory Components to Latest Versions

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-software-factory#14]
### Describe what should be investigated or refactored
A clear and concise description of what should be changed/researched. Ex. This piece of the code is not DRY enough [...]

### Links to any relevant code
(optional) i.e. - https://github.com/defenseunicorns/uds-software-factory/blob/main/README.md?plain=1#L1

### Additional context

```[tasklist]
### Tasks
- [ ] https://github.com/defenseunicorns/uds-package-gitlab/pull/42
- [ ] https://github.com/defenseunicorns/uds-package-gitlab-runner/pull/34
- [ ] https://github.com/defenseunicorns/uds-package-sonarqube/issues/17
- [ ] https://github.com/defenseunicorns/uds-package-mattermost/pull/19
- [ ] https://github.com/defenseunicorns/uds-software-factory/pull/1
```

**Comment by zachariahmiller** [comment]
closing this since its kind of neverending
