### ISSUE TITLE
Align Repo Structures and source charts to be consistent

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-software-factory#15]
### Describe what should be investigated or refactored
Title says it all. This is an issue in the SWF repo to track issues identified with more specificity in their specific repos. 
Add any other context or screenshots about the technical debt here.

```[tasklist]
### Tasks
- [ ] https://github.com/defenseunicorns/uds-package-mattermost/issues/29
- [ ] https://github.com/defenseunicorns/uds-package-sonarqube/issues/43
- [ ] https://github.com/defenseunicorns/uds-package-gitlab/issues/16
```
