### ISSUE TITLE
Conslidate github PR test workflows to uds-common and reference them in the individual packages

### ISSUE THREAD

**Issue by ericwyles** [defenseunicorns/uds-software-factory#17]
### Describe what should be investigated or refactored
Currently each package has duplicated github workflows for pull-requests, scorecard, and tag-and-release. These should be moved to uds-common where they can be shared and referenced from each package.

### Links to any relevant code
(optional) i.e. - https://github.com/defenseunicorns/uds-software-factory/blob/main/README.md?plain=1#L1

### Additional context
Add any other context or screenshots about the technical debt here.

```[tasklist]
### Tasks
- [x] https://github.com/defenseunicorns/uds-common/pull/62
- [x] https://github.com/defenseunicorns/uds-package-gitlab-runner/pull/55
- [x] https://github.com/defenseunicorns/uds-package-mattermost/pull/36
- [x] https://github.com/defenseunicorns/uds-package-sonarqube/pull/54
- [ ] https://github.com/defenseunicorns/uds-package-gitlab/pull/63
```

**Comment by ericwyles** [comment]
Closing this one. If there are further things we need to consolidate to do with scorecard or doc shim we can track that in another issue. Didn't want to leave this one "in progress" to myself with nothing happening.
