### ISSUE TITLE
Implement upgrade tests in all of the single package repos so that we can have higher confidence in success with the full SWF upgrade tests we will need to implement in this repo. 

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-software-factory#18]
### Is your feature request related to a problem? Please describe.
We need to test basic upgrade processes of the single packages for SWF in order to increase confidence and hedge against risk of burning compute and cycles when testing upgrades in the SWF integration repo. This is currently lacking in the single package repos and is necessary for us to be efficient in our work. This issue is to create a set of uds tasks that will run an upgrade process and then update CI to run install and upgrade tests in this repo. For an example look at how it is being done in uds core for the full tests in that repo:

https://github.com/defenseunicorns/uds-core/blob/d2d005b9caf0b067f850f752a3d6e643c99a74c6/tasks/test.yaml#L36

also for reference the matrix of that (just a reference, for us it should be less complicated for these package repos as they are not mono repos) https://github.com/defenseunicorns/uds-core/blob/d2d005b9caf0b067f850f752a3d6e643c99a74c6/.github/workflows/pull-request-conditionals.yaml#L64

Order of operation-wise, there is an open issue for implementing this in the gitlab repo. That will probably be by far the most complicated and should be done first. Based on the output of that a similar pattern should be able to be applied to the other pacakge repos. For those i have added a tasklist below to this issue to track. 

```[tasklist]
### Tasks
- [ ] https://github.com/defenseunicorns/uds-package-gitlab/issues/58
- [ ] Implement upgrade test for sonarqube
- [ ] Implement upgrade test for mattermost
- [x] Implement upgrade test for gitlab runner
```
