### ISSUE TITLE
Add testing of release artifacts before publish on release workflows in each package repo

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-software-factory#30]
### Describe what should be investigated or refactored
Currently, we test artifacts before creating a release and then upon creating a release we build them again and then publish without testing. This can cause an issue where we could pull in (for example) a bad, updated registry1 image and we cant have absolute confidence the published artifact works. This issue will be to update the flow on release as follows:

Create Release -> build packages supporting the release -> test the built packages by deploying them -> on successful deploy, publish the artifacts to OCI.

The below task list represents each repo where this will need to be implemented. 

```[tasklist]
### Tasks
- [ ] https://github.com/defenseunicorns/uds-package-sonarqube/issues/84
- [ ] https://github.com/defenseunicorns/uds-package-gitlab/issues/139
- [ ] https://github.com/defenseunicorns/uds-package-gitlab-runner/issues/86
- [ ] https://github.com/defenseunicorns/uds-package-mattermost/issues/84
- [ ] https://github.com/defenseunicorns/uds-package-postgres-operator/issues/31
- [ ] https://github.com/defenseunicorns/uds-package-valkey/issues/11
```
