### ISSUE TITLE
Fix the Copyright statement in all package LICENSE files.

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-software-factory#64]
### Describe what should be investigated or refactored
Currently our package license files contain the boilerplate `Copyright [yyyy] [name of copyright owner]` this should be updated to `Copyright 2024 Defense Unicorns`.

### Links to any relevant code

https://github.com/defenseunicorns/uds-software-factory/blob/main/LICENSE#L189
https://github.com/defenseunicorns/uds-package-sonarqube/blob/main/LICENSE#L189
https://github.com/defenseunicorns/uds-package-mattermost/blob/main/LICENSE#L189
https://github.com/defenseunicorns/uds-package-gitlab/blob/main/LICENSE#L189
https://github.com/defenseunicorns/uds-package-gitlab-runner/blob/main/LICENSE#L189
https://github.com/defenseunicorns/uds-package-postgres-operator/blob/main/LICENSE#L189

### Additional context

This likely affects LICENSE files beyond the SWF realm since this was an artifact of the UDS Capability repo.
```[tasklist]
### Tasks
- [x] update uds software factory license
- [x] update uds sonarqube license
- [x] update uds mattermost license
- [x] update uds gitlab license
- [x] update uds gitlab runner license
- [x] update uds postgres license
```
